services:
  - type: web
    name: bus-owner
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app --workers=1 --threads=4
    envVars:
      - key: CUPO_TOTAL
        value: "40"
      - key: HORA_CIERRE
        value: "18:00"
      - key: TZ_NAME
        value: "America/Santiago"
      - key: MAIL_TO
        value: "ejejejeje@gmail.com"
      - key: MAIL_FROM
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: CRON_SECRET
        sync: false
